version: '3.4'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: shoppinglistserver
      MYSQL_USER: ShoppingListDBUser
      MYSQL_PASSWORD: mysql-password-1234
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  shoppinglistserver:
    depends_on:
      - db
    image: shoppinglistserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5678:5678

volumes:
  dbdata: