version: '3.4'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: shoppinglistserver
      MYSQL_USER: ShoppingListDBUser
      MYSQL_PASSWORD: mysql-password-1234
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  shoppinglistserver:
    depends_on:
      - db
    image: shoppinglistserver
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: # mount the ssl certificate files folder in the docker image
        - shoppingdata:/app/data # must be the same folder name as DataStorageFolder (appsettings.json)
        - type: bind
          source: /etc/letsencrypt/kestrel/ # this folder contains the certificat files
          target: /app/cert-files/
    ports:
      - 5678:5678

volumes:
  dbdata:
  shoppingdata: